---
# tasks file for logstash
- name: Load a variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Choose platform based task
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'system/{{ ansible_os_family }}.yml'
    - 'system/not-supported.yml'
  loop_control:
    loop_var: platform

- name: Install requirements
  package:
    name: '{{ requirements }}'
    state: present
  register: installed_packages
  until: installed_packages is succeeded
  become: True

- name: SSL preparation
  include_tasks: 'ssl/{{ ansible_system }}.yml'
  when:
    - logstash_enable_ssl

- name: Logstash configuration
  include_tasks: 'configure/{{ ansible_system }}.yml'

- name: Logstash service
  service:
    name: logstash
    state: '{{ (logstash_service_start) | ternary('started','stopped') }}'
    enabled: '{{ logstash_service_autostart }}'
  become: True
