---
# tasks file for logstash
- name: Choose platform based task
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'system/{{ ansible_os_family }}.yml'
    - 'system/not-supported.yml'
  loop_control:
    loop_var: platform

- name: SSL preparation
  include_tasks: 'ssl/{{ ansible_system }}.yml'
  when:
    - logstash_enable_ssl

- name: Logstash configuration
  include_tasks: 'configure/{{ ansible_system }}.yml'
