---
- block:
  - name: Install apt-transport-https
    package:
      name: apt-transport-https
      state: present
    register: installed_transport
    until: installed_transport is succeeded

  - name: Elastic Import latest logstash GPG Key
    apt_key:
      url: '{{ elastic_gpg_key }}'
      state: present
    register: install_key
    until: install_key is succeeded

  - name: Add elasticsearch repo
    apt_repository:
      repo: '{{ es_apt_url }}'
      state: present
      update_cache: True
      filename: '{{ es_repo_file }}.list'
    when: es_use_repository | bool

  - name: Debian - Installing Logstash package
    apt:
      name: >
        {% if logstash_custom_package_url is defined %}{{ logstash_custom_package_url }}
        {% else %} logstash-{{ es_version }}{% endif %}
      state: present
      force: False
    register: installed_package
    until: installed_package is succeeded
    environment:
      LS_JAVA_OPTS: '{{ ls_java_opts }}'
  become: True
