---
#Create KeyStore
- name: Check that Logstash keystore exists
  stat:
    path: "{{ ls_conf_dir }}/logstash.keystore"
  register: keystore_exists

- name: Create Logstash keystore
  become: true
  shell: "export LOGSTASH_KEYSTORE_PASS={{ ls_keystore_pass }} && {{ ls_home }}/bin/logstash-keystore create --path.settings {{ ls_conf_dir }}"
  when:  not keystore_exists.stat.exists
  ignore_errors: true

- name: Add SSL Key Passphrase to Keystore
  become: true
  shell: "export LOGSTASH_KEYSTORE_PASS={{ ls_keystore_pass }} && echo {{ ls_ssl_key_passphrase }}| {{ ls_home }}/bin/logstash-keystore add SSL_KEY_PASSPHRASE  --path.settings {{ ls_conf_dir }} --force"
  when: ls_ssl_key_passphrase and ls_enable_ssl

- name: Add Elasticsearch User to Keystore
  become: true
  shell: "export LOGSTASH_KEYSTORE_PASS={{ ls_keystore_pass }} && echo {{ ls_es_user }}| {{ ls_home }}/bin/logstash-keystore add ES_USER  --path.settings {{ ls_conf_dir }} --force"
  when: ls_es_user and ls_enable_keystore

- name: Add Elasticsearch Password to Keystore
  become: true
  shell: "export LOGSTASH_KEYSTORE_PASS={{ ls_keystore_pass }} && echo {{ ls_es_pass }}| {{ ls_home }}/bin/logstash-keystore add ES_PASS  --path.settings {{ ls_conf_dir }} --force"
  when: ls_es_pass and ls_enable_keystore

- name: Add Elasticsearch Keystore Password to Keystore
  become: true
  shell: "export LOGSTASH_KEYSTORE_PASS={{ ls_keystore_pass }} && echo {{ es_keystore_pass }}| {{ ls_home }}/bin/logstash-keystore add ES_KEYSTORE_PASS  --path.settings {{ ls_conf_dir }} --force"
  when: es_keystore_pass and ls_enable_keystore

- name: Add Elasticsearch Truststore Password to Keystore
  become: true
  shell: "export LOGSTASH_KEYSTORE_PASS={{ ls_keystore_pass }} && echo {{ es_truststore_pass }}| {{ ls_home }}/bin/logstash-keystore add ES_TRUSTSTORE_PASS  --path.settings {{ ls_conf_dir }} --force"
  when: es_truststore_pass and ls_enable_keystore
